use_frameworks!

platform :ios, '10.0'

target 'aoao-plus-train-ios_Example' do
  pod 'aoao-plus-train-ios', :path => '../'

  target 'aoao-plus-train-ios_Tests' do
    inherit! :search_paths

    
  end
end
